import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'Terms of Service' }

export default function TermsPage() {
  const year = new Date().getFullYear()
  return (
    <div className="min-h-screen bg-white flex flex-col">
      <header className="border-b border-zinc-200">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/" className="text-lg font-semibold tracking-tight text-zinc-900">Replova</a>
          <a href="/signin" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">Sign in</a>
        </div>
      </header>
      <div className="flex-1 max-w-2xl mx-auto px-6 py-16 w-full">
        <h1 className="text-3xl font-bold text-zinc-900 mb-2">Terms of Service</h1>
        <p className="text-zinc-400 text-sm mb-10">Last updated: January 1, {year}</p>

        <div className="prose prose-zinc max-w-none space-y-8 text-sm text-zinc-700 leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-zinc-900 mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using Replova ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-zinc-900 mb-2">2. Description of Service</h2>
            <p>Replova provides AI-generated reply drafts for Google reviews. We fetch publicly available reviews via the Google Places API, generate reply suggestions using AI, and deliver them to you via weekly email. You are responsible for reviewing and approving any reply before posting it publicly.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-zinc-900 mb-2">3. Subscription and Billing</h2>
            <p>Replova is a paid subscription service at $99/month after a 30-day free trial. You may cancel at any time via the billing portal in your dashboard. Cancellations take effect at the end of the current billing period. No refunds are issued for partial months.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-zinc-900 mb-2">4. AI-Generated Content</h2>
            <p>Reply drafts are generated by AI and are suggestions only. Replova does not guarantee their accuracy, tone, or suitability. You are solely responsible for any content you post publicly. Always review drafts before use.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-zinc-900 mb-2">5. Acceptable Use</h2>
            <p>You agree not to use the Service for any unlawful purpose, to post harmful or misleading content, or to violate Google's Terms of Service. We reserve the right to terminate accounts that abuse the Service.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-zinc-900 mb-2">6. Limitation of Liability</h2>
            <p>Replova is provided "as is." To the maximum extent permitted by law, we disclaim all warranties and shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-zinc-900 mb-2">7. Contact</h2>
            <p>Questions about these terms? Email us at <a href="mailto:support@replova.app" className="text-zinc-900 underline">support@replova.app</a>.</p>
          </section>
        </div>
      </div>
      <footer className="border-t border-zinc-200 py-5 px-6">
        <p className="text-center text-sm text-zinc-400">© {year} Replova. All rights reserved.</p>
      </footer>
    </div>
  )
}
