import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'Terms of Service — Replova' }

export default function TermsPage() {
  const year = new Date().getFullYear()
  return (
    <div className="min-h-dvh bg-white flex flex-col">
      <header className="border-b border-zinc-200 sticky top-0 bg-white/95 backdrop-blur z-10">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/" className="text-base font-semibold tracking-tight text-zinc-900">Replova</a>
          <a href="/signin" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">Sign in</a>
        </div>
      </header>

      <div className="flex-1 max-w-2xl mx-auto px-6 py-14 w-full fade-up">
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-zinc-900 tracking-tight mb-2">Terms of Service</h1>
          <p className="text-zinc-400 text-sm">Last updated: January 1, {year}</p>
        </div>

        <div className="space-y-8 text-sm text-zinc-600 leading-relaxed">
          {[
            {
              title: '1. Acceptance of Terms',
              body: 'By accessing or using Replova ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.',
            },
            {
              title: '2. Description of Service',
              body: 'Replova provides AI-generated reply drafts for Google reviews. We fetch publicly available reviews via the Google Places API, generate reply suggestions using AI, and deliver them to you via weekly email. You are responsible for reviewing and approving any reply before posting it publicly.',
            },
            {
              title: '3. Subscription and Billing',
              body: 'Replova is a paid subscription service at $99/month after a 30-day free trial. You may cancel at any time via the billing portal in your dashboard. Cancellations take effect at the end of the current billing period. No refunds are issued for partial months.',
            },
            {
              title: '4. AI-Generated Content',
              body: 'Reply drafts are generated by AI and are suggestions only. Replova does not guarantee their accuracy, tone, or suitability. You are solely responsible for any content you post publicly. Always review drafts before use.',
            },
            {
              title: '5. Acceptable Use',
              body: "You agree not to use the Service for any unlawful purpose, to post harmful or misleading content, or to violate Google's Terms of Service. We reserve the right to terminate accounts that abuse the Service.",
            },
            {
              title: '6. Limitation of Liability',
              body: 'Replova is provided "as is." To the maximum extent permitted by law, we disclaim all warranties and shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.',
            },
            {
              title: '7. Contact',
              body: null,
              contact: true,
            },
          ].map(({ title, body, contact }) => (
            <section key={title}>
              <h2 className="text-base font-semibold text-zinc-900 mb-2">{title}</h2>
              {body && <p>{body}</p>}
              {contact && (
                <p>
                  Questions about these terms? Email us at{' '}
                  <a href="mailto:support@replova.app" className="text-zinc-900 underline underline-offset-2 hover:text-blue-600 transition-colors">
                    support@replova.app
                  </a>.
                </p>
              )}
            </section>
          ))}
        </div>
      </div>

      <footer className="border-t border-zinc-200">
        <div className="max-w-6xl mx-auto px-6 py-5 flex flex-col sm:flex-row items-center justify-between gap-3">
          <span className="text-sm font-semibold text-zinc-900">Replova</span>
          <div className="flex items-center gap-5">
            <a href="/privacy" className="text-xs text-zinc-400 hover:text-zinc-700 transition-colors">Privacy</a>
            <a href="mailto:support@replova.app" className="text-xs text-zinc-400 hover:text-zinc-700 transition-colors">Support</a>
            <span className="text-xs text-zinc-400">© {year} Replova</span>
          </div>
        </div>
      </footer>
    </div>
  )
}
