// ── Legal pages, emails, mobile, canvas, empty state ───────────────────────
const { useState: useStateL } = React;

function LegalPage({ route }) {
  const nav = (p) => window.__nav(p);
  const which = route === '/privacy' ? 'privacy' : route === '/refunds' ? 'refunds' : 'terms';

  const docs = {
    terms: {
      title: 'Terms of Service',
      kicker: 'Effective April 1, 2026',
      sections: [
        { h: '1. The thing you signed up for', p: 'Replova ("we") provides reputation management software for restaurants. You ("you") use the service to read and respond to public reviews of your business. We charge a monthly fee. You can cancel any time.' },
        { h: '2. Your account', p: 'You are responsible for keeping your sign-in email secure. We don\'t use passwords. If your inbox is compromised, that is sufficient access for someone to sign in as you.' },
        { h: '3. Connected services', p: 'When you connect Google Business, we receive read access to reviews on the connected listing(s) and write access to post replies. We use this access only for the features advertised in the product.' },
        { h: '4. Replies we post', p: 'AI drafts are suggestions, not statements made by Replova. Replies posted to Google appear under your account; you are responsible for their content. Auto-reply (if enabled) is bounded by the conditions you set in Settings.' },
        { h: '5. Plans, billing, refunds', p: 'Plans renew monthly. Trial is 30 days, no card required. After trial, your card is charged at the start of each month. We refund any unused full month if you cancel by mistake — see the refunds page.' },
        { h: '6. The boring legal bits', p: 'Service is provided "as is." We are not liable for indirect damages. Either party can terminate with 30 days notice. Disputes are resolved in New York.' },
      ],
    },
    privacy: {
      title: 'Privacy Policy',
      kicker: 'Effective April 1, 2026',
      sections: [
        { h: '1. What we collect', p: 'Your email, your restaurant\'s name and address, the contents of public reviews on your connected listing, and the replies you post. Stripe handles your payment information; we never see card details.' },
        { h: '2. What we don\'t collect', p: 'No browser fingerprints, no third-party advertising trackers, no behavioral analytics. We use one first-party cookie to keep you signed in.' },
        { h: '3. AI drafts', p: 'Reply drafts are generated by Anthropic\'s Claude API. Review text is sent to Anthropic to generate the draft and then discarded. Your data is not used to train any model.' },
        { h: '4. Who can see your data', p: 'You. Two engineers on our team, when investigating an account-specific support ticket. Nobody else.' },
        { h: '5. Deletion', p: 'Click "Delete account" in Settings → Danger zone. We delete everything within 24 hours, including backups.' },
      ],
    },
    refunds: {
      title: 'Refunds',
      kicker: 'Plain English',
      sections: [
        { h: 'Trial', p: 'You\'re not charged for the trial. Cancel by day 30 and pay nothing.' },
        { h: 'Cancel by mistake', p: 'If you cancel within 7 days of being charged and email us, we\'ll refund the full month, no questions.' },
        { h: 'Mid-month cancellation', p: 'If you cancel after 7 days, you keep access for the rest of the month. We don\'t pro-rate.' },
        { h: 'How', p: 'Email support@replova.app. We aim to reply within an hour during US business hours, two hours otherwise.' },
      ],
    },
  };

  const doc = docs[which];

  return (
    <div style={{ minHeight:'100dvh', background:'var(--bg)', display:'flex', flexDirection:'column' }}>
      <MarketingNav/>
      <main style={{ flex:1, maxWidth:760, width:'100%', margin:'0 auto', padding:'72px 32px' }}>
        <div className="t-eyebrow" style={{ marginBottom:14 }}>{doc.kicker}</div>
        <h1 className="t-serif" style={{ fontSize:56, lineHeight:1.05, letterSpacing:'-0.02em', marginBottom:18 }}>{doc.title}</h1>
        <div style={{ display:'flex', gap:16, paddingBottom:32, borderBottom:'1px solid var(--line)' }}>
          {['terms','privacy','refunds'].map(k => (
            <button key={k} onClick={()=>nav('/'+k)} style={{
              fontSize:13, fontWeight: which===k ? 600 : 400,
              color: which===k ? 'var(--t1)' : 'var(--t3)',
              textTransform:'capitalize',
              borderBottom: which===k ? '1px solid var(--t1)' : '1px solid transparent',
              paddingBottom:6,
            }}>{k}</button>
          ))}
        </div>
        <div style={{ marginTop:40 }}>
          {doc.sections.map((s, i) => (
            <section key={i} style={{ marginBottom:36, display:'grid', gridTemplateColumns:'48px 1fr', gap:24 }}>
              <div className="t-mono c-t4" style={{ fontSize:11, paddingTop:5 }}>§{(i+1).toString().padStart(2,'0')}</div>
              <div>
                <h2 className="t-serif" style={{ fontSize:22, lineHeight:1.2, letterSpacing:'-0.01em', marginBottom:10 }}>{s.h}</h2>
                <p className="t-body c-t2" style={{ fontSize:15, lineHeight:1.7 }}>{s.p}</p>
              </div>
            </section>
          ))}
        </div>
        <div style={{ paddingTop:32, borderTop:'1px solid var(--line)', display:'flex', justifyContent:'space-between', fontSize:12, color:'var(--t3)' }}>
          <span>Questions? <a href="mailto:legal@replova.app" style={{ color:'var(--t1)', textDecoration:'underline' }}>legal@replova.app</a></span>
          <span>v 4.2</span>
        </div>
      </main>
      <MarketingFooter/>
    </div>
  );
}

// ── Empty state — first sign-in (signature moment 3) ─────────────────────────
function EmptyStatePage({ tweaks }) {
  const mode = tweaks?.emptyStyle || 'editorial';
  return (
    <div className="app">
      <Sidebar active="/dashboard"/>
      <div className="main">
        <TopBar>
          <span style={{ color:'var(--t2)' }}>Workspace</span>
          <Ico.chevRight s={10}/>
          <span style={{ color:'var(--t1)', fontWeight:600 }}>Reviews</span>
        </TopBar>

        <div className="page-body" style={{ paddingTop:48 }}>
          {mode === 'editorial' && (
            <div style={{ maxWidth:760, margin:'80px auto', textAlign:'center' }}>
              <div className="t-eyebrow" style={{ marginBottom:24 }}>Welcome to Replova</div>
              <h1 className="t-serif" style={{ fontSize:64, lineHeight:1.05, letterSpacing:'-0.02em', marginBottom:24 }}>
                The first review<br/>
                <span style={{ fontStyle:'italic', color:'var(--t3)' }}>arrives shortly.</span>
              </h1>
              <p className="t-body c-t2" style={{ fontSize:16, maxWidth:520, margin:'0 auto 40px', lineHeight:1.7 }}>
                We're importing the last 90 days of reviews from Google Business. This usually takes under a minute. While you wait — three things worth doing.
              </p>
              <div style={{ display:'grid', gridTemplateColumns:'repeat(3, 1fr)', gap:14, textAlign:'left', marginBottom:48 }}>
                {[
                  { n:'01', t:'Set your tone', b:'Tell us how you usually reply. We\'ll match it.', cta:'Settings →', goto:'/dashboard/settings' },
                  { n:'02', t:'Pick competitors', b:'Three nearby restaurants you compete with.', cta:'Add some →', goto:'/dashboard/competitors' },
                  { n:'03', t:'Send a request', b:'Email regulars who haven\'t left a review yet.', cta:'Upload CSV →', goto:'/dashboard/review-requests' },
                ].map(c => (
                  <button key={c.n} onClick={()=>window.__nav(c.goto)} className="card" style={{ padding:20, textAlign:'left' }}>
                    <div className="t-mono c-accent" style={{ fontSize:11, marginBottom:14 }}>{c.n}</div>
                    <div className="t-h3" style={{ marginBottom:6 }}>{c.t}</div>
                    <div className="t-xs c-t3" style={{ marginBottom:14, lineHeight:1.5 }}>{c.b}</div>
                    <div className="t-xs" style={{ color:'var(--accent)', fontWeight:600 }}>{c.cta}</div>
                  </button>
                ))}
              </div>

              <div className="card-inset" style={{ padding:18, display:'inline-flex', alignItems:'center', gap:12, fontSize:13 }}>
                <div className="dot dot-warn dot-pulse"/>
                <span className="c-t2">Sync in progress · <span className="t-mono c-t3">142 reviews · ~30s remaining</span></span>
              </div>
            </div>
          )}
          {mode === 'minimal' && (
            <div style={{ maxWidth:480, margin:'140px auto', textAlign:'center' }}>
              <div className="dot dot-warn dot-pulse" style={{ width:8, height:8, margin:'0 auto 18px' }}/>
              <h1 className="t-serif" style={{ fontSize:36, marginBottom:10 }}>Syncing reviews</h1>
              <p className="t-sm c-t3">142 reviews from Google Business · about 30 seconds</p>
            </div>
          )}
          {mode === 'tutorial' && (
            <div style={{ maxWidth:760, margin:'48px auto' }}>
              <h1 className="t-h1" style={{ marginBottom:8 }}>Welcome, Maria</h1>
              <p className="t-body c-t3" style={{ marginBottom:32 }}>Three quick wins in your first ten minutes.</p>
              <div style={{ border:'1px solid var(--line)', borderRadius:10, overflow:'hidden' }}>
                {[
                  { d:true, t:'Connect Google Business', s:'Done · imported 142 reviews' },
                  { d:false, t:'Set your reply tone', s:'2 minutes' },
                  { d:false, t:'Add 3 competitors', s:'1 minute' },
                  { d:false, t:'Send your first review request', s:'Upload a CSV' },
                ].map((s, i) => (
                  <div key={i} style={{ display:'flex', alignItems:'center', gap:16, padding:'16px 20px', borderTop: i>0?'1px solid var(--line)':'none', background: s.d?'var(--surface-2)':'transparent' }}>
                    <div style={{ width:22, height:22, borderRadius:'50%', border:'1.5px solid', borderColor: s.d?'var(--pos)':'var(--line-md)', background: s.d?'var(--pos)':'transparent', color: s.d?'#fff':'var(--t3)', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>
                      {s.d ? <Ico.check s={11} sw={3}/> : <span className="t-mono" style={{ fontSize:10 }}>{i+1}</span>}
                    </div>
                    <div style={{ flex:1 }}>
                      <div style={{ fontSize:14, fontWeight:600, color: s.d?'var(--t3)':'var(--t1)', textDecoration: s.d?'line-through':'none' }}>{s.t}</div>
                      <div className="t-xs c-t3">{s.s}</div>
                    </div>
                    {!s.d && <button className="btn btn-ghost btn-sm">Start</button>}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { LegalPage, EmptyStatePage });
